version: '3.1'

services:
  newimage:
    image: newimage
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - newimage_data:/app/data

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: exampledb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  newimage_data:
  mysql_data:
