version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel_lms
      MYSQL_USER: root
      MYSQL_PASSWORD: xspl#!#!@123
      MYSQL_ROOT_PASSWORD: root_password
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_lms 
      DB_USERNAME: root
      DB_PASSWORD: xspl#!#!@123

